export const partnerTypes = {
    PARTNER_ACTION_START: "PARTNER_ACTION_START",
    PARTNER_GET_SUCCESS: "PARTNER_GET_SUCCESS",
    PARTNER_GET_FAILED: "PARTNER_GET_FAILED",
    PARTNER_ACTION_END: "PARTNER_ACTION_END",
}
