export const aboutUsTypes = {
    ABOUT_US_ACTION_START: "ABOUT_US_ACTION_START",
    ABOUT_US_GET_SUCCESS: "ABOUT_US_GET_SUCCESS",
    ABOUT_US_GET_FAILED: "ABOUT_US_GET_FAILED",
    ABOUT_US_ACTION_END: "ABOUT_US_ACTION_END",
}
