export const loneInstructionTypes = {
    LONE_INSTRUCTION_ACTION_START: "LONE_INSTRUCTION_ACTION_START",
    LONE_INSTRUCTION_GET_SUCCESS: "LONE_INSTRUCTION_GET_SUCCESS",
    LONE_INSTRUCTION_GET_FAILED: "LONE_INSTRUCTION_GET_FAILED",
    LONE_INSTRUCTION_ACTION_END: "LONE_INSTRUCTION_ACTION_END",
}
