export const propertyTypes = {
    PROPERTY_ACTION_START: "PROPERTY_ACTION_START",
    PROPERTY_GET_SUCCESS: "PROPERTY_GET_SUCCESS",
    PROPERTY_GET_FAILED: "PROPERTY_GET_FAILED",
    PROPERTY_ACTION_END: "PROPERTY_ACTION_END",
}
