export const areaGuideDetailsTypes = {
    AREA_GUIDE_DETAILS_ACTION_START: "AREA_GUIDE_DETAILS_ACTION_START",
    AREA_GUIDE_DETAILS_GET_SUCCESS: "AREA_GUIDE_DETAILS_GET_SUCCESS",
    AREA_GUIDE_DETAILS_GET_FAILED: "AREA_GUIDE_DETAILS_GET_FAILED",
    AREA_GUIDE_DETAILS_ACTION_END: "AREA_GUIDE_DETAILS_ACTION_END",
}
