export const blogDetailsTypes = {
    BLOG_DETAILS_ACTION_START: "BLOG_DETAILS_ACTION_START",
    BLOG_DETAILS_GET_SUCCESS: "BLOG_DETAILS_GET_SUCCESS",
    BLOG_DETAILS_GET_FAILED: "BLOG_DETAILS_GET_FAILED",
    BLOG_DETAILS_ACTION_END: "BLOG_DETAILS_ACTION_END",
}
