export const cityListTypes = {
    CITY_LIST_ACTION_START: "CITY_LIST_ACTION_START",
    CITY_LIST_GET_SUCCESS: "CITY_LIST_GET_SUCCESS",
    CITY_LIST_GET_FAILED: "CITY_LIST_GET_FAILED",
    CITY_LIST_ACTION_END: "CITY_LIST_ACTION_END",
}
