export const hotPropertyTypes = {
    HOT_PROPERTY_ACTION_START: "HOT_PROPERTY_ACTION_START",
    HOT_PROPERTY_GET_SUCCESS: "HOT_PROPERTY_GET_SUCCESS",
    HOT_PROPERTY_GET_FAILED: "HOT_PROPERTY_GET_FAILED",
    HOT_PROPERTY_ACTION_END: "HOT_PROPERTY_ACTION_END",
}
