export const propertyDetailsTypes = {
    PROPERTY_DETAILS_ACTION_START: "PROPERTY_DETAILS_ACTION_START",
    PROPERTY_DETAILS_GET_SUCCESS: "PROPERTY_DETAILS_GET_SUCCESS",
    PROPERTY_DETAILS_GET_FAILED: "PROPERTY_DETAILS_GET_FAILED",
    PROPERTY_DETAILS_ACTION_END: "PROPERTY_DETAILS_ACTION_END",
}
