export const urgentPropertyTypes = {
    URGENT_PROPERTY_ACTION_START: "URGENT_PROPERTY_ACTION_START",
    URGENT_PROPERTY_GET_SUCCESS: "URGENT_PROPERTY_GET_SUCCESS",
    URGENT_PROPERTY_GET_FAILED: "URGENT_PROPERTY_GET_FAILED",
    URGENT_PROPERTY_ACTION_END: "URGENT_PROPERTY_ACTION_END",
}
