export const landSalesTypes = {
    LAND_SALES_ACTION_START: "LAND_SALES_ACTION_START",
    LAND_SALES_GET_SUCCESS: "LAND_SALES_GET_SUCCESS",
    LAND_SALES_GET_FAILED: "LAND_SALES_GET_FAILED",
    LAND_SALES_ACTION_END: "LAND_SALES_ACTION_END",
}
