export const contactUsTypes = {
    CONTACT_US_ACTION_START: "CONTACT_US_ACTION_START",
    CONTACT_US_GET_SUCCESS: "CONTACT_US_GET_SUCCESS",
    CONTACT_US_GET_FAILED: "CONTACT_US_GET_FAILED",
    CONTACT_US_ACTION_END: "CONTACT_US_ACTION_END",
}
