export const interiorDetailsTypes = {
    INTERIOR_DETAILS_ACTION_START: "INTERIOR_DETAILS_ACTION_START",
    INTERIOR_DETAILS_GET_SUCCESS: "INTERIOR_DETAILS_GET_SUCCESS",
    INTERIOR_DETAILS_GET_FAILED: "INTERIOR_DETAILS_GET_FAILED",
    INTERIOR_DETAILS_ACTION_END: "INTERIOR_DETAILS_ACTION_END",
}
