export const ptypeCstatusTypes = {
    PTYPE_CSTATUS_ACTION_START: "PTYPE_CSTATUS_ACTION_START",
    PTYPE_CSTATUS_GET_SUCCESS: "PTYPE_CSTATUS_GET_SUCCESS",
    PTYPE_CSTATUS_GET_FAILED: "PTYPE_CSTATUS_GET_FAILED",
    PTYPE_CSTATUS_ACTION_END: "PTYPE_CSTATUS_ACTION_END",
}
