export const latestPropertyTypes = {
    LATEST_PROPERTY_ACTION_START: "LATEST_PROPERTY_ACTION_START",
    LATEST_PROPERTY_GET_SUCCESS: "LATEST_PROPERTY_GET_SUCCESS",
    LATEST_PROPERTY_GET_FAILED: "LATEST_PROPERTY_GET_FAILED",
    LATEST_PROPERTY_ACTION_END: "LATEST_PROPERTY_ACTION_END",
}
