export const interiorTypes = {
    INTERIOR_ACTION_START: "INTERIOR_ACTION_START",
    INTERIOR_GET_SUCCESS: "INTERIOR_GET_SUCCESS",
    INTERIOR_GET_FAILED: "INTERIOR_GET_FAILED",
    INTERIOR_ACTION_END: "INTERIOR_ACTION_END",
}
