export const buySaleGuideDetailsTypes = {
    BUY_SALE_GUIDE_DETAILS_ACTION_START: "BUY_SALE_GUIDE_DETAILS_ACTION_START",
    BUY_SALE_GUIDE_DETAILS_GET_SUCCESS: "BUY_SALE_GUIDE_DETAILS_GET_SUCCESS",
    BUY_SALE_GUIDE_DETAILS_GET_FAILED: "BUY_SALE_GUIDE_DETAILS_GET_FAILED",
    BUY_SALE_GUIDE_DETAILS_ACTION_END: "BUY_SALE_GUIDE_DETAILS_ACTION_END",
}
