export const loanBankTypes = {
    LOAN_BANK_ACTION_START: "LOAN_BANK_ACTION_START",
    LOAN_BANK_GET_SUCCESS: "LOAN_BANK_GET_SUCCESS",
    LOAN_BANK_GET_FAILED: "LOAN_BANK_GET_FAILED",
    LOAN_BANK_ACTION_END: "LOAN_BANK_ACTION_END",
}
