export const areaGuideTypes = {
    AREA_GUIDE_ACTION_START: "AREA_GUIDE_ACTION_START",
    AREA_GUIDE_GET_SUCCESS: "AREA_GUIDE_GET_SUCCESS",
    AREA_GUIDE_GET_FAILED: "AREA_GUIDE_GET_FAILED",
    AREA_GUIDE_ACTION_END: "AREA_GUIDE_ACTION_END",
}
