export const landSalesDetailsTypes = {
    LAND_SALES_DETAILS_ACTION_START: "LAND_SALES_DETAILS_ACTION_START",
    LAND_SALES_DETAILS_GET_SUCCESS: "LAND_SALES_DETAILS_GET_SUCCESS",
    LAND_SALES_DETAILS_GET_FAILED: "LAND_SALES_DETAILS_GET_FAILED",
    LAND_SALES_DETAILS_ACTION_END: "LAND_SALES_DETAILS_ACTION_END",
}
