export const addProperty = {
    ADD_PROPERTY_ACTION_START: "ADD_PROPERTY_ACTION_START",
    ADD_PROPERTY_GET_SUCCESS: "ADD_PROPERTY_GET_SUCCESS",
    ADD_PROPERTY_GET_FAILED: "ADD_PROPERTY_GET_FAILED",
    ADD_PROPERTY_ACTION_END: "ADD_PROPERTY_ACTION_END",
}
