export const locationTypes = {
    LOCATION_ACTION_START: "LOCATION_ACTION_START",
    LOCATION_GET_SUCCESS: "LOCATION_GET_SUCCESS",
    LOCATION_GET_FAILED: "LOCATION_GET_FAILED",
    LOCATION_ACTION_END: "LOCATION_ACTION_END",
}
