export const loanBenefitTypes = {
    LOAN_BENEFIT_ACTION_START: "LOAN_BENEFIT_ACTION_START",
    LOAN_BENEFIT_GET_SUCCESS: "LOAN_BENEFIT_GET_SUCCESS",
    LOAN_BENEFIT_GET_FAILED: "LOAN_BENEFIT_GET_FAILED",
    LOAN_BENEFIT_ACTION_END: "LOAN_BENEFIT_ACTION_END",
}
